### ISSUE TITLE
Running the program each time?

### ISSUE THREAD

**Issue by HenryB09** [cracrayol/ZUIKI_to_JRE#2]
Hi I am back.   I went to use today and it did not work.  So I went in to run yr program as I did yesterday.   And then it worked.  Do I have to go through this method to connect each time or is there a short cut?  Cheers Henry

**Comment by cracrayol** [comment]
You have to run this program each time you want to use the Zuiki Mascon with JRETS.
But this program will no more be necessary after the next update of JRETS (that will come next tuesday - 28/05) as JRETS will natively support the Zuiki Controller (as announced on the latest news : https://steamcommunity.com/games/2111630/announcements/detail/5991554339561022033).

**Comment by HenryB09** [comment]
Thank you. Valuable information.

**Comment by jaoxford** [comment]
Thanks for this, can anybody confirm that the controller now works out the box?

**Comment by cracrayol** [comment]
I have the ZKNS-001 and I confirm that with the last update, I can play JRETS with the Zuiki without external program. The process for setting up the controller is in the latest revision of the JRETS manual.

**Comment by jaoxford** [comment]
Thanks, got it to work!
